/**
 * tests/<my_program>.ts — ts-mocha test skeleton (Anchor 1.x, @anchor-lang/core).
 *
 * Use this if you scaffolded with `--test-template mocha`. (Anchor 1.x's DEFAULT template
 * is LiteSVM/Rust; see examples/tests/ for LiteSVM + Mollusk patterns.) A mocha suite runs
 * against whatever `[provider] cluster` points at — a local Surfpool/test-validator, devnet, etc.
 *
 * IMPORTANT: the TS client is `@anchor-lang/core` in Anchor 1.x — NOT `@coral-xyz/anchor`
 * (that package is frozen at 0.32.1). Mixing the two breaks type resolution.
 *
 * Run:  anchor test            # boots the validator, deploys, runs this suite
 *   or  anchor run test        # if the validator/programs are already up
 *
 * Deps: @anchor-lang/core@1.1.2  @solana/web3.js@^1.98  ts-mocha  mocha  chai  @types/*
 */

import * as anchor from "@anchor-lang/core";
import { Program } from "@anchor-lang/core";
import { PublicKey } from "@solana/web3.js";
import { assert } from "chai";

// Generated by `anchor build` from your program's IDL. TODO: rename `MyProgram`/`my_program`.
import { MyProgram } from "../target/types/my_program";

describe("my_program", () => {
  // Reads ANCHOR_PROVIDER_URL + ANCHOR_WALLET (set by `anchor test`).
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Workspace key is the PascalCase program name. Program is 2-arg in 1.x (id comes from the IDL).
  const program = anchor.workspace.MyProgram as Program<MyProgram>;
  const authority = provider.wallet.publicKey;

  it("initializes the state PDA", async () => {
    // TODO: match your program's seeds (see SEED_STATE in the program).
    const [statePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("state"), authority.toBuffer()],
      program.programId,
    );

    await program.methods
      .initialize()
      // `.accounts()` is strict about resolvable accounts; use `.accountsPartial()` if you must
      // pass an account Anchor could otherwise infer.
      .accountsPartial({ state: statePda, authority })
      .rpc();

    const state = await program.account.state.fetch(statePda);
    assert.strictEqual(state.value.toNumber(), 0);
    assert.ok(state.authority.equals(authority));
  });

  // TODO: add more `it(...)` blocks. To assert a program error:
  //
  // it("rejects an unauthorized update", async () => {
  //   try {
  //     await program.methods.update(new anchor.BN(1)).accountsPartial({ state: statePda, authority: attacker.publicKey })
  //       .signers([attacker]).rpc();
  //     assert.fail("should have thrown");
  //   } catch (err) {
  //     assert.strictEqual((err as anchor.AnchorError).error.errorCode.code, "Unauthorized");
  //   }
  // });
});
