// Counter program test — ts-mocha + @anchor-lang/core (1.1.2).
//
// IMPORTANT: import from `@anchor-lang/core`, NOT `@coral-xyz/anchor` (frozen at
// 0.32.1). The two scopes ship incompatible `Program`/`BN` types — never mix them.
//
// Run with: anchor test --test-template mocha   (or wire up ts-mocha directly).
// `anchor test` sets ANCHOR_PROVIDER_URL + ANCHOR_WALLET, which AnchorProvider.env() reads.

import * as anchor from "@anchor-lang/core";
import { Program, BorshCoder, EventParser } from "@anchor-lang/core";
import { Counter } from "../target/types/counter"; // generated by `anchor build`
import { assert } from "chai";

describe("counter", () => {
  // Configure the client from the environment (cluster URL + wallet keypair).
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // Workspace key is the PascalCase of the program module name (`counter` -> `Counter`).
  // Typed as `Program<Counter>` so `.methods`, `.account`, and `.idl` are fully typed.
  const program = anchor.workspace.Counter as Program<Counter>;

  const authority = provider.wallet;

  // Derive the counter PDA exactly as the program does: seeds = [b"counter", authority].
  const [counterPda, counterBump] = anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("counter"), authority.publicKey.toBuffer()],
    program.programId
  );

  it("initializes the counter at zero", async () => {
    await program.methods
      .initialize()
      // `.accountsPartial` (not `.accounts`): the counter PDA is auto-resolvable from its
      // seeds, so the strict `.accounts()` type rejects it — pass it explicitly here.
      .accountsPartial({
        authority: authority.publicKey,
        counter: counterPda,
        systemProgram: anchor.web3.SystemProgram.programId,
      })
      .rpc();

    const counter = await program.account.counter.fetch(counterPda);
    assert.strictEqual(counter.count.toNumber(), 0);
    assert.isTrue(counter.authority.equals(authority.publicKey));
    assert.strictEqual(counter.bump, counterBump); // program stored the canonical bump
  });

  it("increments and emits CountChanged", async () => {
    const signature = await program.methods
      .increment()
      // `.accountsPartial` (not `.accounts`): the counter PDA is auto-resolvable from its
      // seeds, so the strict `.accounts()` type rejects it — pass it explicitly here.
      .accountsPartial({
        authority: authority.publicKey,
        counter: counterPda,
      })
      .rpc({ commitment: "confirmed" });

    // 1. Assert the on-chain state advanced.
    const counter = await program.account.counter.fetch(counterPda);
    assert.strictEqual(counter.count.toNumber(), 1);

    // 2. Assert the emitted event by parsing the confirmed transaction's logs.
    //    This is deterministic (no websocket race vs. addEventListener).
    const tx = await provider.connection.getTransaction(signature, {
      commitment: "confirmed",
      maxSupportedTransactionVersion: 0,
    });
    const parser = new EventParser(program.programId, new BorshCoder(program.idl));
    const events = [...parser.parseLogs(tx!.meta!.logMessages!)];

    // Tolerate either casing of the event name across IDL versions.
    const event = events.find((e) => e.name.toLowerCase() === "countchanged");
    assert.isOk(event, "expected a CountChanged event");
    assert.strictEqual(event!.data.count.toNumber(), 1);
    assert.isTrue(event!.data.authority.equals(authority.publicKey));
  });
});
